### ISSUE TITLE
doesnt work in firefox - compiled plugin

### ISSUE THREAD

**Issue by kaiaeberli** [toaarnio/webcl-firefox#80]
Hi,

I tried compiling this and added the xpi plugin, but it doesnt work.

I ran the Nokia test suite, and it just prompts me to install webcl again - when i do that and restart, it just asks me again, so seems not to recognise it.

Any ideas?

Kai

**Comment by abarragan** [comment]
It has been 2 years and half since last update.

**Comment by kaiaeberli** [comment]
fair enough, do you know if there is anything working out there? I need this to get gpu matrix multiplication on javascript going with this library - https://github.com/mil-tokyo/sushi2

**Comment by abarragan** [comment]
I think you could try downloading FF 32 or 34 and running on it, that *should* work. But yeah, it's just a nasty workaround. Sorry for not being much help.

**Comment by MirrorTM** [comment]
You could try making matrix multiplication in a fragment shader and render the results to a float32 texture , or on the other hand using webgl2 do the multiplication in the vertex shader and returning the result through transform feedback

**Comment by MirrorTM** [comment]
To preform  the***

**Comment by kaiaeberli** [comment]
ok thanks might try it

**Comment by VincentSC** [comment]
Take a look at http://glmatrix.net/

**Comment by kaiaeberli** [comment]
i checked, but it can only do 4x4 matrices
